// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: common.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TestAPIKeyRequest represents a request to validate an API key
type TestAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestAPIKeyRequest) Reset() {
	*x = TestAPIKeyRequest{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestAPIKeyRequest) ProtoMessage() {}

func (x *TestAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*TestAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// TestAPIKeyResponse provides information about the validated API key
type TestAPIKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the API key is valid
	IsValid bool `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	// Whether the API key is active (not revoked)
	IsActive bool `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	// Masked version of the API key (first 8 characters)
	KeyPrefix string `protobuf:"bytes,3,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"`
	// User information associated with the API key
	User *UserInfo `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	// Project information (if API key is project-scoped)
	Project *ProjectInfo `protobuf:"bytes,5,opt,name=project,proto3,oneof" json:"project,omitempty"`
	// Organization information
	Organization *OrganizationInfo `protobuf:"bytes,6,opt,name=organization,proto3,oneof" json:"organization,omitempty"`
	// Permissions granted to this API key
	Permissions map[string]bool `protobuf:"bytes,7,rep,name=permissions,proto3" json:"permissions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Correlation ID for tracking
	CorrelationId string `protobuf:"bytes,8,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// API key metadata
	Metadata      *APIKeyMetadata `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestAPIKeyResponse) Reset() {
	*x = TestAPIKeyResponse{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestAPIKeyResponse) ProtoMessage() {}

func (x *TestAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*TestAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *TestAPIKeyResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *TestAPIKeyResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *TestAPIKeyResponse) GetKeyPrefix() string {
	if x != nil {
		return x.KeyPrefix
	}
	return ""
}

func (x *TestAPIKeyResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *TestAPIKeyResponse) GetProject() *ProjectInfo {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *TestAPIKeyResponse) GetOrganization() *OrganizationInfo {
	if x != nil {
		return x.Organization
	}
	return nil
}

func (x *TestAPIKeyResponse) GetPermissions() map[string]bool {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *TestAPIKeyResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *TestAPIKeyResponse) GetMetadata() *APIKeyMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// UserInfo contains basic user information
type UserInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// User email
	Email         string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *UserInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// ProjectInfo contains basic project information
type ProjectInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Project name
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectInfo) Reset() {
	*x = ProjectInfo{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectInfo) ProtoMessage() {}

func (x *ProjectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectInfo.ProtoReflect.Descriptor instead.
func (*ProjectInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProjectInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// OrganizationInfo contains basic organization information
type OrganizationInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Organization ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Organization name
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationInfo) Reset() {
	*x = OrganizationInfo{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationInfo) ProtoMessage() {}

func (x *OrganizationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationInfo.ProtoReflect.Descriptor instead.
func (*OrganizationInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *OrganizationInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrganizationInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// APIKeyMetadata contains metadata about the API key
type APIKeyMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When the API key was created
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// When the API key was last used
	LastUsedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_used_at,json=lastUsedAt,proto3,oneof" json:"last_used_at,omitempty"`
	// Rate limit configuration
	RateLimit *RateLimitInfo `protobuf:"bytes,3,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	// Usage statistics
	UsageStats    *UsageStats `protobuf:"bytes,4,opt,name=usage_stats,json=usageStats,proto3" json:"usage_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKeyMetadata) Reset() {
	*x = APIKeyMetadata{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeyMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyMetadata) ProtoMessage() {}

func (x *APIKeyMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyMetadata.ProtoReflect.Descriptor instead.
func (*APIKeyMetadata) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *APIKeyMetadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *APIKeyMetadata) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

func (x *APIKeyMetadata) GetRateLimit() *RateLimitInfo {
	if x != nil {
		return x.RateLimit
	}
	return nil
}

func (x *APIKeyMetadata) GetUsageStats() *UsageStats {
	if x != nil {
		return x.UsageStats
	}
	return nil
}

// RateLimitInfo contains rate limiting information
type RateLimitInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Requests per second limit
	RequestsPerSecond int32 `protobuf:"varint,1,opt,name=requests_per_second,json=requestsPerSecond,proto3" json:"requests_per_second,omitempty"`
	// Burst limit
	Burst int32 `protobuf:"varint,2,opt,name=burst,proto3" json:"burst,omitempty"`
	// Current remaining requests
	Remaining int32 `protobuf:"varint,3,opt,name=remaining,proto3" json:"remaining,omitempty"`
	// When the rate limit resets
	ResetAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=reset_at,json=resetAt,proto3" json:"reset_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitInfo) Reset() {
	*x = RateLimitInfo{}
	mi := &file_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitInfo) ProtoMessage() {}

func (x *RateLimitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitInfo.ProtoReflect.Descriptor instead.
func (*RateLimitInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

func (x *RateLimitInfo) GetRequestsPerSecond() int32 {
	if x != nil {
		return x.RequestsPerSecond
	}
	return 0
}

func (x *RateLimitInfo) GetBurst() int32 {
	if x != nil {
		return x.Burst
	}
	return 0
}

func (x *RateLimitInfo) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *RateLimitInfo) GetResetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ResetAt
	}
	return nil
}

// UsageStats contains API usage statistics
type UsageStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total requests made with this API key
	TotalRequests int64 `protobuf:"varint,1,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	// Total emails sent
	EmailsSent int64 `protobuf:"varint,2,opt,name=emails_sent,json=emailsSent,proto3" json:"emails_sent,omitempty"`
	// Usage in the current billing period
	CurrentPeriodUsage int64 `protobuf:"varint,3,opt,name=current_period_usage,json=currentPeriodUsage,proto3" json:"current_period_usage,omitempty"`
	// Billing period start
	PeriodStart *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	// Billing period end
	PeriodEnd     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageStats) Reset() {
	*x = UsageStats{}
	mi := &file_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageStats) ProtoMessage() {}

func (x *UsageStats) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageStats.ProtoReflect.Descriptor instead.
func (*UsageStats) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{7}
}

func (x *UsageStats) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *UsageStats) GetEmailsSent() int64 {
	if x != nil {
		return x.EmailsSent
	}
	return 0
}

func (x *UsageStats) GetCurrentPeriodUsage() int64 {
	if x != nil {
		return x.CurrentPeriodUsage
	}
	return 0
}

func (x *UsageStats) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *UsageStats) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

// RequestMetadata can be included in any request for additional tracking
type RequestMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Correlation ID for distributed tracing
	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Client-specified timeout for this request
	Timeout *durationpb.Duration `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Request priority (0-10, higher = more important)
	Priority int32 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	// Client information
	Client        *ClientInfo `protobuf:"bytes,4,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMetadata) Reset() {
	*x = RequestMetadata{}
	mi := &file_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMetadata) ProtoMessage() {}

func (x *RequestMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMetadata.ProtoReflect.Descriptor instead.
func (*RequestMetadata) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{8}
}

func (x *RequestMetadata) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *RequestMetadata) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *RequestMetadata) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *RequestMetadata) GetClient() *ClientInfo {
	if x != nil {
		return x.Client
	}
	return nil
}

// ClientInfo identifies the SDK client
type ClientInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SDK language (go, python, js, etc.)
	SdkLanguage string `protobuf:"bytes,1,opt,name=sdk_language,json=sdkLanguage,proto3" json:"sdk_language,omitempty"`
	// SDK version
	SdkVersion string `protobuf:"bytes,2,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	// Client application name
	AppName string `protobuf:"bytes,3,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	// Client application version
	AppVersion    string `protobuf:"bytes,4,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	mi := &file_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{9}
}

func (x *ClientInfo) GetSdkLanguage() string {
	if x != nil {
		return x.SdkLanguage
	}
	return ""
}

func (x *ClientInfo) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *ClientInfo) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *ClientInfo) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\fhuefy.sdk.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x13\n" +
	"\x11TestAPIKeyRequest\"\xad\x04\n" +
	"\x12TestAPIKeyResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12\x1b\n" +
	"\tis_active\x18\x02 \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"key_prefix\x18\x03 \x01(\tR\tkeyPrefix\x12*\n" +
	"\x04user\x18\x04 \x01(\v2\x16.huefy.sdk.v1.UserInfoR\x04user\x128\n" +
	"\aproject\x18\x05 \x01(\v2\x19.huefy.sdk.v1.ProjectInfoH\x00R\aproject\x88\x01\x01\x12G\n" +
	"\forganization\x18\x06 \x01(\v2\x1e.huefy.sdk.v1.OrganizationInfoH\x01R\forganization\x88\x01\x01\x12S\n" +
	"\vpermissions\x18\a \x03(\v21.huefy.sdk.v1.TestAPIKeyResponse.PermissionsEntryR\vpermissions\x12%\n" +
	"\x0ecorrelation_id\x18\b \x01(\tR\rcorrelationId\x128\n" +
	"\bmetadata\x18\t \x01(\v2\x1c.huefy.sdk.v1.APIKeyMetadataR\bmetadata\x1a>\n" +
	"\x10PermissionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01B\n" +
	"\n" +
	"\b_projectB\x0f\n" +
	"\r_organization\"0\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"1\n" +
	"\vProjectInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"6\n" +
	"\x10OrganizationInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x96\x02\n" +
	"\x0eAPIKeyMetadata\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12A\n" +
	"\flast_used_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"lastUsedAt\x88\x01\x01\x12:\n" +
	"\n" +
	"rate_limit\x18\x03 \x01(\v2\x1b.huefy.sdk.v1.RateLimitInfoR\trateLimit\x129\n" +
	"\vusage_stats\x18\x04 \x01(\v2\x18.huefy.sdk.v1.UsageStatsR\n" +
	"usageStatsB\x0f\n" +
	"\r_last_used_at\"\xaa\x01\n" +
	"\rRateLimitInfo\x12.\n" +
	"\x13requests_per_second\x18\x01 \x01(\x05R\x11requestsPerSecond\x12\x14\n" +
	"\x05burst\x18\x02 \x01(\x05R\x05burst\x12\x1c\n" +
	"\tremaining\x18\x03 \x01(\x05R\tremaining\x125\n" +
	"\breset_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aresetAt\"\x80\x02\n" +
	"\n" +
	"UsageStats\x12%\n" +
	"\x0etotal_requests\x18\x01 \x01(\x03R\rtotalRequests\x12\x1f\n" +
	"\vemails_sent\x18\x02 \x01(\x03R\n" +
	"emailsSent\x120\n" +
	"\x14current_period_usage\x18\x03 \x01(\x03R\x12currentPeriodUsage\x12=\n" +
	"\fperiod_start\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\"\xbb\x01\n" +
	"\x0fRequestMetadata\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x120\n" +
	"\x06client\x18\x04 \x01(\v2\x18.huefy.sdk.v1.ClientInfoR\x06client\"\x8c\x01\n" +
	"\n" +
	"ClientInfo\x12!\n" +
	"\fsdk_language\x18\x01 \x01(\tR\vsdkLanguage\x12\x1f\n" +
	"\vsdk_version\x18\x02 \x01(\tR\n" +
	"sdkVersion\x12\x19\n" +
	"\bapp_name\x18\x03 \x01(\tR\aappName\x12\x1f\n" +
	"\vapp_version\x18\x04 \x01(\tR\n" +
	"appVersionB7Z5github.com/teracrafts/huefy-sdk/core/kernel/pb/sdk/v1b\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_common_proto_goTypes = []any{
	(*TestAPIKeyRequest)(nil),     // 0: huefy.sdk.v1.TestAPIKeyRequest
	(*TestAPIKeyResponse)(nil),    // 1: huefy.sdk.v1.TestAPIKeyResponse
	(*UserInfo)(nil),              // 2: huefy.sdk.v1.UserInfo
	(*ProjectInfo)(nil),           // 3: huefy.sdk.v1.ProjectInfo
	(*OrganizationInfo)(nil),      // 4: huefy.sdk.v1.OrganizationInfo
	(*APIKeyMetadata)(nil),        // 5: huefy.sdk.v1.APIKeyMetadata
	(*RateLimitInfo)(nil),         // 6: huefy.sdk.v1.RateLimitInfo
	(*UsageStats)(nil),            // 7: huefy.sdk.v1.UsageStats
	(*RequestMetadata)(nil),       // 8: huefy.sdk.v1.RequestMetadata
	(*ClientInfo)(nil),            // 9: huefy.sdk.v1.ClientInfo
	nil,                           // 10: huefy.sdk.v1.TestAPIKeyResponse.PermissionsEntry
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 12: google.protobuf.Duration
}
var file_common_proto_depIdxs = []int32{
	2,  // 0: huefy.sdk.v1.TestAPIKeyResponse.user:type_name -> huefy.sdk.v1.UserInfo
	3,  // 1: huefy.sdk.v1.TestAPIKeyResponse.project:type_name -> huefy.sdk.v1.ProjectInfo
	4,  // 2: huefy.sdk.v1.TestAPIKeyResponse.organization:type_name -> huefy.sdk.v1.OrganizationInfo
	10, // 3: huefy.sdk.v1.TestAPIKeyResponse.permissions:type_name -> huefy.sdk.v1.TestAPIKeyResponse.PermissionsEntry
	5,  // 4: huefy.sdk.v1.TestAPIKeyResponse.metadata:type_name -> huefy.sdk.v1.APIKeyMetadata
	11, // 5: huefy.sdk.v1.APIKeyMetadata.created_at:type_name -> google.protobuf.Timestamp
	11, // 6: huefy.sdk.v1.APIKeyMetadata.last_used_at:type_name -> google.protobuf.Timestamp
	6,  // 7: huefy.sdk.v1.APIKeyMetadata.rate_limit:type_name -> huefy.sdk.v1.RateLimitInfo
	7,  // 8: huefy.sdk.v1.APIKeyMetadata.usage_stats:type_name -> huefy.sdk.v1.UsageStats
	11, // 9: huefy.sdk.v1.RateLimitInfo.reset_at:type_name -> google.protobuf.Timestamp
	11, // 10: huefy.sdk.v1.UsageStats.period_start:type_name -> google.protobuf.Timestamp
	11, // 11: huefy.sdk.v1.UsageStats.period_end:type_name -> google.protobuf.Timestamp
	12, // 12: huefy.sdk.v1.RequestMetadata.timeout:type_name -> google.protobuf.Duration
	9,  // 13: huefy.sdk.v1.RequestMetadata.client:type_name -> huefy.sdk.v1.ClientInfo
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_common_proto_msgTypes[1].OneofWrappers = []any{}
	file_common_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
