// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: email.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RecipientType defines the type of email recipient
type RecipientType int32

const (
	RecipientType_RECIPIENT_TYPE_UNSPECIFIED RecipientType = 0
	RecipientType_RECIPIENT_TYPE_TO          RecipientType = 1
	RecipientType_RECIPIENT_TYPE_CC          RecipientType = 2
	RecipientType_RECIPIENT_TYPE_BCC         RecipientType = 3
)

// Enum value maps for RecipientType.
var (
	RecipientType_name = map[int32]string{
		0: "RECIPIENT_TYPE_UNSPECIFIED",
		1: "RECIPIENT_TYPE_TO",
		2: "RECIPIENT_TYPE_CC",
		3: "RECIPIENT_TYPE_BCC",
	}
	RecipientType_value = map[string]int32{
		"RECIPIENT_TYPE_UNSPECIFIED": 0,
		"RECIPIENT_TYPE_TO":          1,
		"RECIPIENT_TYPE_CC":          2,
		"RECIPIENT_TYPE_BCC":         3,
	}
)

func (x RecipientType) Enum() *RecipientType {
	p := new(RecipientType)
	*p = x
	return p
}

func (x RecipientType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecipientType) Descriptor() protoreflect.EnumDescriptor {
	return file_email_proto_enumTypes[0].Descriptor()
}

func (RecipientType) Type() protoreflect.EnumType {
	return &file_email_proto_enumTypes[0]
}

func (x RecipientType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecipientType.Descriptor instead.
func (RecipientType) EnumDescriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{0}
}

// EmailStatus represents the delivery status of an email
type EmailStatus int32

const (
	EmailStatus_EMAIL_STATUS_UNSPECIFIED  EmailStatus = 0
	EmailStatus_EMAIL_STATUS_QUEUED       EmailStatus = 1  // Email is queued for sending
	EmailStatus_EMAIL_STATUS_SENDING      EmailStatus = 2  // Email is being sent
	EmailStatus_EMAIL_STATUS_SENT         EmailStatus = 3  // Email was sent to provider
	EmailStatus_EMAIL_STATUS_FAILED       EmailStatus = 4  // Email failed to send
	EmailStatus_EMAIL_STATUS_BOUNCED      EmailStatus = 5  // Email bounced
	EmailStatus_EMAIL_STATUS_DELIVERED    EmailStatus = 6  // Email was delivered to recipient
	EmailStatus_EMAIL_STATUS_OPENED       EmailStatus = 7  // Email was opened by recipient
	EmailStatus_EMAIL_STATUS_CLICKED      EmailStatus = 8  // Link in email was clicked
	EmailStatus_EMAIL_STATUS_COMPLAINED   EmailStatus = 9  // Recipient marked as spam
	EmailStatus_EMAIL_STATUS_UNSUBSCRIBED EmailStatus = 10 // Recipient unsubscribed
)

// Enum value maps for EmailStatus.
var (
	EmailStatus_name = map[int32]string{
		0:  "EMAIL_STATUS_UNSPECIFIED",
		1:  "EMAIL_STATUS_QUEUED",
		2:  "EMAIL_STATUS_SENDING",
		3:  "EMAIL_STATUS_SENT",
		4:  "EMAIL_STATUS_FAILED",
		5:  "EMAIL_STATUS_BOUNCED",
		6:  "EMAIL_STATUS_DELIVERED",
		7:  "EMAIL_STATUS_OPENED",
		8:  "EMAIL_STATUS_CLICKED",
		9:  "EMAIL_STATUS_COMPLAINED",
		10: "EMAIL_STATUS_UNSUBSCRIBED",
	}
	EmailStatus_value = map[string]int32{
		"EMAIL_STATUS_UNSPECIFIED":  0,
		"EMAIL_STATUS_QUEUED":       1,
		"EMAIL_STATUS_SENDING":      2,
		"EMAIL_STATUS_SENT":         3,
		"EMAIL_STATUS_FAILED":       4,
		"EMAIL_STATUS_BOUNCED":      5,
		"EMAIL_STATUS_DELIVERED":    6,
		"EMAIL_STATUS_OPENED":       7,
		"EMAIL_STATUS_CLICKED":      8,
		"EMAIL_STATUS_COMPLAINED":   9,
		"EMAIL_STATUS_UNSUBSCRIBED": 10,
	}
)

func (x EmailStatus) Enum() *EmailStatus {
	p := new(EmailStatus)
	*p = x
	return p
}

func (x EmailStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmailStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_email_proto_enumTypes[1].Descriptor()
}

func (EmailStatus) Type() protoreflect.EnumType {
	return &file_email_proto_enumTypes[1]
}

func (x EmailStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmailStatus.Descriptor instead.
func (EmailStatus) EnumDescriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{1}
}

// SendEmailRequest represents a request to send a single email
type SendEmailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Template key identifying the email template to use
	TemplateKey string `protobuf:"bytes,1,opt,name=template_key,json=templateKey,proto3" json:"template_key,omitempty"`
	// Optional template version (uses latest if not specified)
	TemplateVersion *int32 `protobuf:"varint,2,opt,name=template_version,json=templateVersion,proto3,oneof" json:"template_version,omitempty"`
	// Dynamic data to inject into the template
	Data *structpb.Struct `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// Email recipient information
	Recipient *EmailRecipient `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// Optional custom sender email (overrides template default)
	FromEmail *string `protobuf:"bytes,5,opt,name=from_email,json=fromEmail,proto3,oneof" json:"from_email,omitempty"`
	// Optional sender display name
	FromName *string `protobuf:"bytes,6,opt,name=from_name,json=fromName,proto3,oneof" json:"from_name,omitempty"`
	// Optional reply-to address
	ReplyTo *string `protobuf:"bytes,7,opt,name=reply_to,json=replyTo,proto3,oneof" json:"reply_to,omitempty"`
	// Optional email provider to use (ses, sendgrid, mailgun, mailchimp)
	ProviderType *string `protobuf:"bytes,8,opt,name=provider_type,json=providerType,proto3,oneof" json:"provider_type,omitempty"`
	// Optional correlation ID for request tracking
	CorrelationId *string `protobuf:"bytes,9,opt,name=correlation_id,json=correlationId,proto3,oneof" json:"correlation_id,omitempty"`
	// Optional metadata for tracking and analytics
	Metadata map[string]string `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional request options
	Options       *RequestOptions `protobuf:"bytes,11,opt,name=options,proto3,oneof" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailRequest) Reset() {
	*x = SendEmailRequest{}
	mi := &file_email_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRequest) ProtoMessage() {}

func (x *SendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRequest.ProtoReflect.Descriptor instead.
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{0}
}

func (x *SendEmailRequest) GetTemplateKey() string {
	if x != nil {
		return x.TemplateKey
	}
	return ""
}

func (x *SendEmailRequest) GetTemplateVersion() int32 {
	if x != nil && x.TemplateVersion != nil {
		return *x.TemplateVersion
	}
	return 0
}

func (x *SendEmailRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SendEmailRequest) GetRecipient() *EmailRecipient {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *SendEmailRequest) GetFromEmail() string {
	if x != nil && x.FromEmail != nil {
		return *x.FromEmail
	}
	return ""
}

func (x *SendEmailRequest) GetFromName() string {
	if x != nil && x.FromName != nil {
		return *x.FromName
	}
	return ""
}

func (x *SendEmailRequest) GetReplyTo() string {
	if x != nil && x.ReplyTo != nil {
		return *x.ReplyTo
	}
	return ""
}

func (x *SendEmailRequest) GetProviderType() string {
	if x != nil && x.ProviderType != nil {
		return *x.ProviderType
	}
	return ""
}

func (x *SendEmailRequest) GetCorrelationId() string {
	if x != nil && x.CorrelationId != nil {
		return *x.CorrelationId
	}
	return ""
}

func (x *SendEmailRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SendEmailRequest) GetOptions() *RequestOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// EmailRecipient represents an email recipient
type EmailRecipient struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Email address
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// Recipient type (to, cc, bcc)
	Type RecipientType `protobuf:"varint,2,opt,name=type,proto3,enum=huefy.sdk.v1.RecipientType" json:"type,omitempty"`
	// Optional recipient-specific template data
	Data          *structpb.Struct `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailRecipient) Reset() {
	*x = EmailRecipient{}
	mi := &file_email_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailRecipient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailRecipient) ProtoMessage() {}

func (x *EmailRecipient) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailRecipient.ProtoReflect.Descriptor instead.
func (*EmailRecipient) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{1}
}

func (x *EmailRecipient) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailRecipient) GetType() RecipientType {
	if x != nil {
		return x.Type
	}
	return RecipientType_RECIPIENT_TYPE_UNSPECIFIED
}

func (x *EmailRecipient) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

// RequestOptions contains optional request configuration
type RequestOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request timeout duration
	Timeout *durationpb.Duration `protobuf:"bytes,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Request priority (higher number = higher priority)
	Priority int32 `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	// Idempotency key to prevent duplicate sends
	IdempotencyKey string `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestOptions) Reset() {
	*x = RequestOptions{}
	mi := &file_email_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestOptions) ProtoMessage() {}

func (x *RequestOptions) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestOptions.ProtoReflect.Descriptor instead.
func (*RequestOptions) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{2}
}

func (x *RequestOptions) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *RequestOptions) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *RequestOptions) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

// SendEmailResponse represents the response from sending an email
type SendEmailResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the email was successfully queued/sent
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Human-readable status message
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Unique message ID from the email provider
	MessageId string `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Email provider used to send the message
	Provider string `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	// Correlation ID (echoed from request if provided)
	CorrelationId string `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Timestamp when the email was sent
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailResponse) Reset() {
	*x = SendEmailResponse{}
	mi := &file_email_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailResponse) ProtoMessage() {}

func (x *SendEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailResponse.ProtoReflect.Descriptor instead.
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{3}
}

func (x *SendEmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendEmailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendEmailResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendEmailResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *SendEmailResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *SendEmailResponse) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

// SendBulkEmailRequest represents a request to send multiple emails
type SendBulkEmailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of email requests to send
	Emails []*SendEmailRequest `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
	// Optional correlation ID for the entire batch
	CorrelationId *string `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3,oneof" json:"correlation_id,omitempty"`
	// Optional batch processing options
	BatchOptions  *BatchOptions `protobuf:"bytes,3,opt,name=batch_options,json=batchOptions,proto3,oneof" json:"batch_options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBulkEmailRequest) Reset() {
	*x = SendBulkEmailRequest{}
	mi := &file_email_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBulkEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBulkEmailRequest) ProtoMessage() {}

func (x *SendBulkEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBulkEmailRequest.ProtoReflect.Descriptor instead.
func (*SendBulkEmailRequest) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{4}
}

func (x *SendBulkEmailRequest) GetEmails() []*SendEmailRequest {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *SendBulkEmailRequest) GetCorrelationId() string {
	if x != nil && x.CorrelationId != nil {
		return *x.CorrelationId
	}
	return ""
}

func (x *SendBulkEmailRequest) GetBatchOptions() *BatchOptions {
	if x != nil {
		return x.BatchOptions
	}
	return nil
}

// BatchOptions configures batch processing behavior
type BatchOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Continue processing on individual failures
	ContinueOnError bool `protobuf:"varint,1,opt,name=continue_on_error,json=continueOnError,proto3" json:"continue_on_error,omitempty"`
	// Maximum concurrent sends
	MaxConcurrent int32 `protobuf:"varint,2,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchOptions) Reset() {
	*x = BatchOptions{}
	mi := &file_email_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchOptions) ProtoMessage() {}

func (x *BatchOptions) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchOptions.ProtoReflect.Descriptor instead.
func (*BatchOptions) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{5}
}

func (x *BatchOptions) GetContinueOnError() bool {
	if x != nil {
		return x.ContinueOnError
	}
	return false
}

func (x *BatchOptions) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

// SendBulkEmailResponse represents the response from sending bulk emails
type SendBulkEmailResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Results for each email in the batch
	Results []*EmailResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	// Correlation ID (echoed from request if provided)
	CorrelationId string `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Summary statistics
	Stats         *BulkEmailStats `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBulkEmailResponse) Reset() {
	*x = SendBulkEmailResponse{}
	mi := &file_email_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBulkEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBulkEmailResponse) ProtoMessage() {}

func (x *SendBulkEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBulkEmailResponse.ProtoReflect.Descriptor instead.
func (*SendBulkEmailResponse) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{6}
}

func (x *SendBulkEmailResponse) GetResults() []*EmailResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SendBulkEmailResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *SendBulkEmailResponse) GetStats() *BulkEmailStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// EmailResult represents the result of a single email in a bulk operation
type EmailResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether this specific email succeeded
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Response details if successful
	Response *SendEmailResponse `protobuf:"bytes,2,opt,name=response,proto3,oneof" json:"response,omitempty"`
	// Error details if failed
	Error *Error `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	// Index of this email in the original request
	Index         int32 `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailResult) Reset() {
	*x = EmailResult{}
	mi := &file_email_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailResult) ProtoMessage() {}

func (x *EmailResult) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailResult.ProtoReflect.Descriptor instead.
func (*EmailResult) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{7}
}

func (x *EmailResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EmailResult) GetResponse() *SendEmailResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *EmailResult) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *EmailResult) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// BulkEmailStats provides summary statistics for bulk operations
type BulkEmailStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total emails in the batch
	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// Number of successful sends
	Successful int32 `protobuf:"varint,2,opt,name=successful,proto3" json:"successful,omitempty"`
	// Number of failed sends
	Failed int32 `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	// Processing duration
	Duration      *durationpb.Duration `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkEmailStats) Reset() {
	*x = BulkEmailStats{}
	mi := &file_email_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkEmailStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkEmailStats) ProtoMessage() {}

func (x *BulkEmailStats) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkEmailStats.ProtoReflect.Descriptor instead.
func (*BulkEmailStats) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{8}
}

func (x *BulkEmailStats) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BulkEmailStats) GetSuccessful() int32 {
	if x != nil {
		return x.Successful
	}
	return 0
}

func (x *BulkEmailStats) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *BulkEmailStats) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

// EmailStatusUpdate represents a status update for a sent email
type EmailStatusUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message ID being updated
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Current status of the email
	Status EmailStatus `protobuf:"varint,2,opt,name=status,proto3,enum=huefy.sdk.v1.EmailStatus" json:"status,omitempty"`
	// Timestamp of this status update
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Optional error message if status is failed
	ErrorMessage *string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	// Correlation ID for tracking
	CorrelationId *string `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3,oneof" json:"correlation_id,omitempty"`
	// Additional status metadata
	Metadata      map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailStatusUpdate) Reset() {
	*x = EmailStatusUpdate{}
	mi := &file_email_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailStatusUpdate) ProtoMessage() {}

func (x *EmailStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_email_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailStatusUpdate.ProtoReflect.Descriptor instead.
func (*EmailStatusUpdate) Descriptor() ([]byte, []int) {
	return file_email_proto_rawDescGZIP(), []int{9}
}

func (x *EmailStatusUpdate) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *EmailStatusUpdate) GetStatus() EmailStatus {
	if x != nil {
		return x.Status
	}
	return EmailStatus_EMAIL_STATUS_UNSPECIFIED
}

func (x *EmailStatusUpdate) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *EmailStatusUpdate) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *EmailStatusUpdate) GetCorrelationId() string {
	if x != nil && x.CorrelationId != nil {
		return *x.CorrelationId
	}
	return ""
}

func (x *EmailStatusUpdate) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_email_proto protoreflect.FileDescriptor

const file_email_proto_rawDesc = "" +
	"\n" +
	"\vemail.proto\x12\fhuefy.sdk.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\fcommon.proto\x1a\ferrors.proto\"\xbe\x05\n" +
	"\x10SendEmailRequest\x12!\n" +
	"\ftemplate_key\x18\x01 \x01(\tR\vtemplateKey\x12.\n" +
	"\x10template_version\x18\x02 \x01(\x05H\x00R\x0ftemplateVersion\x88\x01\x01\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data\x12:\n" +
	"\trecipient\x18\x04 \x01(\v2\x1c.huefy.sdk.v1.EmailRecipientR\trecipient\x12\"\n" +
	"\n" +
	"from_email\x18\x05 \x01(\tH\x01R\tfromEmail\x88\x01\x01\x12 \n" +
	"\tfrom_name\x18\x06 \x01(\tH\x02R\bfromName\x88\x01\x01\x12\x1e\n" +
	"\breply_to\x18\a \x01(\tH\x03R\areplyTo\x88\x01\x01\x12(\n" +
	"\rprovider_type\x18\b \x01(\tH\x04R\fproviderType\x88\x01\x01\x12*\n" +
	"\x0ecorrelation_id\x18\t \x01(\tH\x05R\rcorrelationId\x88\x01\x01\x12H\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2,.huefy.sdk.v1.SendEmailRequest.MetadataEntryR\bmetadata\x12;\n" +
	"\aoptions\x18\v \x01(\v2\x1c.huefy.sdk.v1.RequestOptionsH\x06R\aoptions\x88\x01\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x13\n" +
	"\x11_template_versionB\r\n" +
	"\v_from_emailB\f\n" +
	"\n" +
	"_from_nameB\v\n" +
	"\t_reply_toB\x10\n" +
	"\x0e_provider_typeB\x11\n" +
	"\x0f_correlation_idB\n" +
	"\n" +
	"\b_options\"\x84\x01\n" +
	"\x0eEmailRecipient\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12/\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1b.huefy.sdk.v1.RecipientTypeR\x04type\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data\"\x8a\x01\n" +
	"\x0eRequestOptions\x123\n" +
	"\atimeout\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"\xde\x01\n" +
	"\x11SendEmailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\x123\n" +
	"\asent_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\"\xe5\x01\n" +
	"\x14SendBulkEmailRequest\x126\n" +
	"\x06emails\x18\x01 \x03(\v2\x1e.huefy.sdk.v1.SendEmailRequestR\x06emails\x12*\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tH\x00R\rcorrelationId\x88\x01\x01\x12D\n" +
	"\rbatch_options\x18\x03 \x01(\v2\x1a.huefy.sdk.v1.BatchOptionsH\x01R\fbatchOptions\x88\x01\x01B\x11\n" +
	"\x0f_correlation_idB\x10\n" +
	"\x0e_batch_options\"a\n" +
	"\fBatchOptions\x12*\n" +
	"\x11continue_on_error\x18\x01 \x01(\bR\x0fcontinueOnError\x12%\n" +
	"\x0emax_concurrent\x18\x02 \x01(\x05R\rmaxConcurrent\"\xa7\x01\n" +
	"\x15SendBulkEmailResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.huefy.sdk.v1.EmailResultR\aresults\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\x122\n" +
	"\x05stats\x18\x03 \x01(\v2\x1c.huefy.sdk.v1.BulkEmailStatsR\x05stats\"\xc6\x01\n" +
	"\vEmailResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12@\n" +
	"\bresponse\x18\x02 \x01(\v2\x1f.huefy.sdk.v1.SendEmailResponseH\x00R\bresponse\x88\x01\x01\x12.\n" +
	"\x05error\x18\x03 \x01(\v2\x13.huefy.sdk.v1.ErrorH\x01R\x05error\x88\x01\x01\x12\x14\n" +
	"\x05index\x18\x04 \x01(\x05R\x05indexB\v\n" +
	"\t_responseB\b\n" +
	"\x06_error\"\x95\x01\n" +
	"\x0eBulkEmailStats\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x1e\n" +
	"\n" +
	"successful\x18\x02 \x01(\x05R\n" +
	"successful\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x05R\x06failed\x125\n" +
	"\bduration\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\bduration\"\xa3\x03\n" +
	"\x11EmailStatusUpdate\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.huefy.sdk.v1.EmailStatusR\x06status\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12(\n" +
	"\rerror_message\x18\x04 \x01(\tH\x00R\ferrorMessage\x88\x01\x01\x12*\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tH\x01R\rcorrelationId\x88\x01\x01\x12I\n" +
	"\bmetadata\x18\x06 \x03(\v2-.huefy.sdk.v1.EmailStatusUpdate.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x10\n" +
	"\x0e_error_messageB\x11\n" +
	"\x0f_correlation_id*u\n" +
	"\rRecipientType\x12\x1e\n" +
	"\x1aRECIPIENT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11RECIPIENT_TYPE_TO\x10\x01\x12\x15\n" +
	"\x11RECIPIENT_TYPE_CC\x10\x02\x12\x16\n" +
	"\x12RECIPIENT_TYPE_BCC\x10\x03*\xb3\x02\n" +
	"\vEmailStatus\x12\x1c\n" +
	"\x18EMAIL_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13EMAIL_STATUS_QUEUED\x10\x01\x12\x18\n" +
	"\x14EMAIL_STATUS_SENDING\x10\x02\x12\x15\n" +
	"\x11EMAIL_STATUS_SENT\x10\x03\x12\x17\n" +
	"\x13EMAIL_STATUS_FAILED\x10\x04\x12\x18\n" +
	"\x14EMAIL_STATUS_BOUNCED\x10\x05\x12\x1a\n" +
	"\x16EMAIL_STATUS_DELIVERED\x10\x06\x12\x17\n" +
	"\x13EMAIL_STATUS_OPENED\x10\a\x12\x18\n" +
	"\x14EMAIL_STATUS_CLICKED\x10\b\x12\x1b\n" +
	"\x17EMAIL_STATUS_COMPLAINED\x10\t\x12\x1d\n" +
	"\x19EMAIL_STATUS_UNSUBSCRIBED\x10\n" +
	"B7Z5github.com/teracrafts/huefy-sdk/core/kernel/pb/sdk/v1b\x06proto3"

var (
	file_email_proto_rawDescOnce sync.Once
	file_email_proto_rawDescData []byte
)

func file_email_proto_rawDescGZIP() []byte {
	file_email_proto_rawDescOnce.Do(func() {
		file_email_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_email_proto_rawDesc), len(file_email_proto_rawDesc)))
	})
	return file_email_proto_rawDescData
}

var file_email_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_email_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_email_proto_goTypes = []any{
	(RecipientType)(0),            // 0: huefy.sdk.v1.RecipientType
	(EmailStatus)(0),              // 1: huefy.sdk.v1.EmailStatus
	(*SendEmailRequest)(nil),      // 2: huefy.sdk.v1.SendEmailRequest
	(*EmailRecipient)(nil),        // 3: huefy.sdk.v1.EmailRecipient
	(*RequestOptions)(nil),        // 4: huefy.sdk.v1.RequestOptions
	(*SendEmailResponse)(nil),     // 5: huefy.sdk.v1.SendEmailResponse
	(*SendBulkEmailRequest)(nil),  // 6: huefy.sdk.v1.SendBulkEmailRequest
	(*BatchOptions)(nil),          // 7: huefy.sdk.v1.BatchOptions
	(*SendBulkEmailResponse)(nil), // 8: huefy.sdk.v1.SendBulkEmailResponse
	(*EmailResult)(nil),           // 9: huefy.sdk.v1.EmailResult
	(*BulkEmailStats)(nil),        // 10: huefy.sdk.v1.BulkEmailStats
	(*EmailStatusUpdate)(nil),     // 11: huefy.sdk.v1.EmailStatusUpdate
	nil,                           // 12: huefy.sdk.v1.SendEmailRequest.MetadataEntry
	nil,                           // 13: huefy.sdk.v1.EmailStatusUpdate.MetadataEntry
	(*structpb.Struct)(nil),       // 14: google.protobuf.Struct
	(*durationpb.Duration)(nil),   // 15: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
	(*Error)(nil),                 // 17: huefy.sdk.v1.Error
}
var file_email_proto_depIdxs = []int32{
	14, // 0: huefy.sdk.v1.SendEmailRequest.data:type_name -> google.protobuf.Struct
	3,  // 1: huefy.sdk.v1.SendEmailRequest.recipient:type_name -> huefy.sdk.v1.EmailRecipient
	12, // 2: huefy.sdk.v1.SendEmailRequest.metadata:type_name -> huefy.sdk.v1.SendEmailRequest.MetadataEntry
	4,  // 3: huefy.sdk.v1.SendEmailRequest.options:type_name -> huefy.sdk.v1.RequestOptions
	0,  // 4: huefy.sdk.v1.EmailRecipient.type:type_name -> huefy.sdk.v1.RecipientType
	14, // 5: huefy.sdk.v1.EmailRecipient.data:type_name -> google.protobuf.Struct
	15, // 6: huefy.sdk.v1.RequestOptions.timeout:type_name -> google.protobuf.Duration
	16, // 7: huefy.sdk.v1.SendEmailResponse.sent_at:type_name -> google.protobuf.Timestamp
	2,  // 8: huefy.sdk.v1.SendBulkEmailRequest.emails:type_name -> huefy.sdk.v1.SendEmailRequest
	7,  // 9: huefy.sdk.v1.SendBulkEmailRequest.batch_options:type_name -> huefy.sdk.v1.BatchOptions
	9,  // 10: huefy.sdk.v1.SendBulkEmailResponse.results:type_name -> huefy.sdk.v1.EmailResult
	10, // 11: huefy.sdk.v1.SendBulkEmailResponse.stats:type_name -> huefy.sdk.v1.BulkEmailStats
	5,  // 12: huefy.sdk.v1.EmailResult.response:type_name -> huefy.sdk.v1.SendEmailResponse
	17, // 13: huefy.sdk.v1.EmailResult.error:type_name -> huefy.sdk.v1.Error
	15, // 14: huefy.sdk.v1.BulkEmailStats.duration:type_name -> google.protobuf.Duration
	1,  // 15: huefy.sdk.v1.EmailStatusUpdate.status:type_name -> huefy.sdk.v1.EmailStatus
	16, // 16: huefy.sdk.v1.EmailStatusUpdate.updated_at:type_name -> google.protobuf.Timestamp
	13, // 17: huefy.sdk.v1.EmailStatusUpdate.metadata:type_name -> huefy.sdk.v1.EmailStatusUpdate.MetadataEntry
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_email_proto_init() }
func file_email_proto_init() {
	if File_email_proto != nil {
		return
	}
	file_common_proto_init()
	file_errors_proto_init()
	file_email_proto_msgTypes[0].OneofWrappers = []any{}
	file_email_proto_msgTypes[4].OneofWrappers = []any{}
	file_email_proto_msgTypes[7].OneofWrappers = []any{}
	file_email_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_email_proto_rawDesc), len(file_email_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_email_proto_goTypes,
		DependencyIndexes: file_email_proto_depIdxs,
		EnumInfos:         file_email_proto_enumTypes,
		MessageInfos:      file_email_proto_msgTypes,
	}.Build()
	File_email_proto = out.File
	file_email_proto_goTypes = nil
	file_email_proto_depIdxs = nil
}
