// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: errors.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorCode defines standard error codes
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0
	// Client errors (4xx equivalent)
	ErrorCode_ERROR_CODE_INVALID_REQUEST   ErrorCode = 1 // Invalid request format or parameters
	ErrorCode_ERROR_CODE_INVALID_API_KEY   ErrorCode = 2 // API key is invalid or missing
	ErrorCode_ERROR_CODE_PERMISSION_DENIED ErrorCode = 3 // API key lacks required permissions
	ErrorCode_ERROR_CODE_NOT_FOUND         ErrorCode = 4 // Resource not found
	ErrorCode_ERROR_CODE_ALREADY_EXISTS    ErrorCode = 5 // Resource already exists
	ErrorCode_ERROR_CODE_RATE_LIMITED      ErrorCode = 6 // Rate limit exceeded
	ErrorCode_ERROR_CODE_QUOTA_EXCEEDED    ErrorCode = 7 // Usage quota exceeded
	ErrorCode_ERROR_CODE_INVALID_TEMPLATE  ErrorCode = 8 // Template validation failed
	ErrorCode_ERROR_CODE_INVALID_RECIPIENT ErrorCode = 9 // Invalid recipient email
	// Server errors (5xx equivalent)
	ErrorCode_ERROR_CODE_INTERNAL_ERROR       ErrorCode = 10 // Internal server error
	ErrorCode_ERROR_CODE_UNAVAILABLE          ErrorCode = 11 // Service temporarily unavailable
	ErrorCode_ERROR_CODE_TIMEOUT              ErrorCode = 12 // Request timeout
	ErrorCode_ERROR_CODE_PROVIDER_ERROR       ErrorCode = 13 // Email provider error
	ErrorCode_ERROR_CODE_TEMPLATE_NOT_FOUND   ErrorCode = 14 // Template does not exist
	ErrorCode_ERROR_CODE_CIRCUIT_BREAKER_OPEN ErrorCode = 15 // Circuit breaker is open
	// Business logic errors
	ErrorCode_ERROR_CODE_SUBSCRIPTION_REQUIRED ErrorCode = 16 // Feature requires subscription
	ErrorCode_ERROR_CODE_DOMAIN_NOT_VERIFIED   ErrorCode = 17 // Sender domain not verified
	ErrorCode_ERROR_CODE_BOUNCE_SUPPRESSED     ErrorCode = 18 // Recipient is bounce suppressed
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:  "ERROR_CODE_UNSPECIFIED",
		1:  "ERROR_CODE_INVALID_REQUEST",
		2:  "ERROR_CODE_INVALID_API_KEY",
		3:  "ERROR_CODE_PERMISSION_DENIED",
		4:  "ERROR_CODE_NOT_FOUND",
		5:  "ERROR_CODE_ALREADY_EXISTS",
		6:  "ERROR_CODE_RATE_LIMITED",
		7:  "ERROR_CODE_QUOTA_EXCEEDED",
		8:  "ERROR_CODE_INVALID_TEMPLATE",
		9:  "ERROR_CODE_INVALID_RECIPIENT",
		10: "ERROR_CODE_INTERNAL_ERROR",
		11: "ERROR_CODE_UNAVAILABLE",
		12: "ERROR_CODE_TIMEOUT",
		13: "ERROR_CODE_PROVIDER_ERROR",
		14: "ERROR_CODE_TEMPLATE_NOT_FOUND",
		15: "ERROR_CODE_CIRCUIT_BREAKER_OPEN",
		16: "ERROR_CODE_SUBSCRIPTION_REQUIRED",
		17: "ERROR_CODE_DOMAIN_NOT_VERIFIED",
		18: "ERROR_CODE_BOUNCE_SUPPRESSED",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":           0,
		"ERROR_CODE_INVALID_REQUEST":       1,
		"ERROR_CODE_INVALID_API_KEY":       2,
		"ERROR_CODE_PERMISSION_DENIED":     3,
		"ERROR_CODE_NOT_FOUND":             4,
		"ERROR_CODE_ALREADY_EXISTS":        5,
		"ERROR_CODE_RATE_LIMITED":          6,
		"ERROR_CODE_QUOTA_EXCEEDED":        7,
		"ERROR_CODE_INVALID_TEMPLATE":      8,
		"ERROR_CODE_INVALID_RECIPIENT":     9,
		"ERROR_CODE_INTERNAL_ERROR":        10,
		"ERROR_CODE_UNAVAILABLE":           11,
		"ERROR_CODE_TIMEOUT":               12,
		"ERROR_CODE_PROVIDER_ERROR":        13,
		"ERROR_CODE_TEMPLATE_NOT_FOUND":    14,
		"ERROR_CODE_CIRCUIT_BREAKER_OPEN":  15,
		"ERROR_CODE_SUBSCRIPTION_REQUIRED": 16,
		"ERROR_CODE_DOMAIN_NOT_VERIFIED":   17,
		"ERROR_CODE_BOUNCE_SUPPRESSED":     18,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_errors_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{0}
}

// Error represents a detailed error response
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error code matching SDK error codes
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable error message
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Detailed error information
	Detail string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	// Correlation ID for tracking
	CorrelationId string `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// When the error occurred
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Additional error metadata
	Metadata map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Retry information if applicable
	RetryInfo     *RetryInfo `protobuf:"bytes,7,opt,name=retry_info,json=retryInfo,proto3,oneof" json:"retry_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Error) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Error) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Error) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Error) GetRetryInfo() *RetryInfo {
	if x != nil {
		return x.RetryInfo
	}
	return nil
}

// RetryInfo provides information about retrying failed requests
type RetryInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the request can be retried
	Retryable bool `protobuf:"varint,1,opt,name=retryable,proto3" json:"retryable,omitempty"`
	// Suggested retry delay
	RetryDelay *durationpb.Duration `protobuf:"bytes,2,opt,name=retry_delay,json=retryDelay,proto3" json:"retry_delay,omitempty"`
	// Maximum number of retry attempts
	MaxAttempts int32 `protobuf:"varint,3,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	// Current attempt number
	AttemptNumber int32 `protobuf:"varint,4,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryInfo) Reset() {
	*x = RetryInfo{}
	mi := &file_errors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryInfo) ProtoMessage() {}

func (x *RetryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryInfo.ProtoReflect.Descriptor instead.
func (*RetryInfo) Descriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{1}
}

func (x *RetryInfo) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *RetryInfo) GetRetryDelay() *durationpb.Duration {
	if x != nil {
		return x.RetryDelay
	}
	return nil
}

func (x *RetryInfo) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *RetryInfo) GetAttemptNumber() int32 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

// ValidationError provides details about request validation failures
type ValidationError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field that failed validation
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// Validation rule that failed
	Rule string `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	// Human-readable error message
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Expected value or format
	Expected string `protobuf:"bytes,4,opt,name=expected,proto3" json:"expected,omitempty"`
	// Actual value provided
	Actual        string `protobuf:"bytes,5,opt,name=actual,proto3" json:"actual,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_errors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{2}
}

func (x *ValidationError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidationError) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationError) GetExpected() string {
	if x != nil {
		return x.Expected
	}
	return ""
}

func (x *ValidationError) GetActual() string {
	if x != nil {
		return x.Actual
	}
	return ""
}

// ErrorDetails can contain additional structured error information
type ErrorDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of validation errors
	ValidationErrors []*ValidationError `protobuf:"bytes,1,rep,name=validation_errors,json=validationErrors,proto3" json:"validation_errors,omitempty"`
	// Provider-specific error code
	ProviderErrorCode string `protobuf:"bytes,2,opt,name=provider_error_code,json=providerErrorCode,proto3" json:"provider_error_code,omitempty"`
	// Provider-specific error message
	ProviderErrorMessage string `protobuf:"bytes,3,opt,name=provider_error_message,json=providerErrorMessage,proto3" json:"provider_error_message,omitempty"`
	// Stack trace (debug mode only)
	StackTrace string `protobuf:"bytes,4,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	// Request ID for support
	RequestId     string `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetails) Reset() {
	*x = ErrorDetails{}
	mi := &file_errors_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails) ProtoMessage() {}

func (x *ErrorDetails) ProtoReflect() protoreflect.Message {
	mi := &file_errors_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails.ProtoReflect.Descriptor instead.
func (*ErrorDetails) Descriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorDetails) GetValidationErrors() []*ValidationError {
	if x != nil {
		return x.ValidationErrors
	}
	return nil
}

func (x *ErrorDetails) GetProviderErrorCode() string {
	if x != nil {
		return x.ProviderErrorCode
	}
	return ""
}

func (x *ErrorDetails) GetProviderErrorMessage() string {
	if x != nil {
		return x.ProviderErrorMessage
	}
	return ""
}

func (x *ErrorDetails) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

func (x *ErrorDetails) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_errors_proto protoreflect.FileDescriptor

const file_errors_proto_rawDesc = "" +
	"\n" +
	"\ferrors.proto\x12\fhuefy.sdk.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xf6\x02\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12=\n" +
	"\bmetadata\x18\x06 \x03(\v2!.huefy.sdk.v1.Error.MetadataEntryR\bmetadata\x12;\n" +
	"\n" +
	"retry_info\x18\a \x01(\v2\x17.huefy.sdk.v1.RetryInfoH\x00R\tretryInfo\x88\x01\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\r\n" +
	"\v_retry_info\"\xaf\x01\n" +
	"\tRetryInfo\x12\x1c\n" +
	"\tretryable\x18\x01 \x01(\bR\tretryable\x12:\n" +
	"\vretry_delay\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"retryDelay\x12!\n" +
	"\fmax_attempts\x18\x03 \x01(\x05R\vmaxAttempts\x12%\n" +
	"\x0eattempt_number\x18\x04 \x01(\x05R\rattemptNumber\"\x89\x01\n" +
	"\x0fValidationError\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x12\n" +
	"\x04rule\x18\x02 \x01(\tR\x04rule\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1a\n" +
	"\bexpected\x18\x04 \x01(\tR\bexpected\x12\x16\n" +
	"\x06actual\x18\x05 \x01(\tR\x06actual\"\x80\x02\n" +
	"\fErrorDetails\x12J\n" +
	"\x11validation_errors\x18\x01 \x03(\v2\x1d.huefy.sdk.v1.ValidationErrorR\x10validationErrors\x12.\n" +
	"\x13provider_error_code\x18\x02 \x01(\tR\x11providerErrorCode\x124\n" +
	"\x16provider_error_message\x18\x03 \x01(\tR\x14providerErrorMessage\x12\x1f\n" +
	"\vstack_trace\x18\x04 \x01(\tR\n" +
	"stackTrace\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId*\xe7\x04\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aERROR_CODE_INVALID_REQUEST\x10\x01\x12\x1e\n" +
	"\x1aERROR_CODE_INVALID_API_KEY\x10\x02\x12 \n" +
	"\x1cERROR_CODE_PERMISSION_DENIED\x10\x03\x12\x18\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\x04\x12\x1d\n" +
	"\x19ERROR_CODE_ALREADY_EXISTS\x10\x05\x12\x1b\n" +
	"\x17ERROR_CODE_RATE_LIMITED\x10\x06\x12\x1d\n" +
	"\x19ERROR_CODE_QUOTA_EXCEEDED\x10\a\x12\x1f\n" +
	"\x1bERROR_CODE_INVALID_TEMPLATE\x10\b\x12 \n" +
	"\x1cERROR_CODE_INVALID_RECIPIENT\x10\t\x12\x1d\n" +
	"\x19ERROR_CODE_INTERNAL_ERROR\x10\n" +
	"\x12\x1a\n" +
	"\x16ERROR_CODE_UNAVAILABLE\x10\v\x12\x16\n" +
	"\x12ERROR_CODE_TIMEOUT\x10\f\x12\x1d\n" +
	"\x19ERROR_CODE_PROVIDER_ERROR\x10\r\x12!\n" +
	"\x1dERROR_CODE_TEMPLATE_NOT_FOUND\x10\x0e\x12#\n" +
	"\x1fERROR_CODE_CIRCUIT_BREAKER_OPEN\x10\x0f\x12$\n" +
	" ERROR_CODE_SUBSCRIPTION_REQUIRED\x10\x10\x12\"\n" +
	"\x1eERROR_CODE_DOMAIN_NOT_VERIFIED\x10\x11\x12 \n" +
	"\x1cERROR_CODE_BOUNCE_SUPPRESSED\x10\x12B7Z5github.com/teracrafts/huefy-sdk/core/kernel/pb/sdk/v1b\x06proto3"

var (
	file_errors_proto_rawDescOnce sync.Once
	file_errors_proto_rawDescData []byte
)

func file_errors_proto_rawDescGZIP() []byte {
	file_errors_proto_rawDescOnce.Do(func() {
		file_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errors_proto_rawDesc), len(file_errors_proto_rawDesc)))
	})
	return file_errors_proto_rawDescData
}

var file_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_errors_proto_goTypes = []any{
	(ErrorCode)(0),                // 0: huefy.sdk.v1.ErrorCode
	(*Error)(nil),                 // 1: huefy.sdk.v1.Error
	(*RetryInfo)(nil),             // 2: huefy.sdk.v1.RetryInfo
	(*ValidationError)(nil),       // 3: huefy.sdk.v1.ValidationError
	(*ErrorDetails)(nil),          // 4: huefy.sdk.v1.ErrorDetails
	nil,                           // 5: huefy.sdk.v1.Error.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 7: google.protobuf.Duration
}
var file_errors_proto_depIdxs = []int32{
	6, // 0: huefy.sdk.v1.Error.timestamp:type_name -> google.protobuf.Timestamp
	5, // 1: huefy.sdk.v1.Error.metadata:type_name -> huefy.sdk.v1.Error.MetadataEntry
	2, // 2: huefy.sdk.v1.Error.retry_info:type_name -> huefy.sdk.v1.RetryInfo
	7, // 3: huefy.sdk.v1.RetryInfo.retry_delay:type_name -> google.protobuf.Duration
	3, // 4: huefy.sdk.v1.ErrorDetails.validation_errors:type_name -> huefy.sdk.v1.ValidationError
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_errors_proto_init() }
func file_errors_proto_init() {
	if File_errors_proto != nil {
		return
	}
	file_errors_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errors_proto_rawDesc), len(file_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errors_proto_goTypes,
		DependencyIndexes: file_errors_proto_depIdxs,
		EnumInfos:         file_errors_proto_enumTypes,
		MessageInfos:      file_errors_proto_msgTypes,
	}.Build()
	File_errors_proto = out.File
	file_errors_proto_goTypes = nil
	file_errors_proto_depIdxs = nil
}
