// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: health.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthCheckRequest allows customizing the health check response
type HealthCheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Include detailed dependency health status
	IncludeDependencies bool `protobuf:"varint,1,opt,name=include_dependencies,json=includeDependencies,proto3" json:"include_dependencies,omitempty"`
	// Include server metrics
	IncludeMetrics bool `protobuf:"varint,2,opt,name=include_metrics,json=includeMetrics,proto3" json:"include_metrics,omitempty"`
	// Include version information
	IncludeVersion bool `protobuf:"varint,3,opt,name=include_version,json=includeVersion,proto3" json:"include_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckRequest) GetIncludeDependencies() bool {
	if x != nil {
		return x.IncludeDependencies
	}
	return false
}

func (x *HealthCheckRequest) GetIncludeMetrics() bool {
	if x != nil {
		return x.IncludeMetrics
	}
	return false
}

func (x *HealthCheckRequest) GetIncludeVersion() bool {
	if x != nil {
		return x.IncludeVersion
	}
	return false
}

// HealthCheckResponse provides comprehensive health status
type HealthCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Overall health status (healthy, degraded, unhealthy)
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Current server timestamp
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// API version
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Health status of dependencies
	Dependencies map[string]*ServiceHealth `protobuf:"bytes,4,rep,name=dependencies,proto3" json:"dependencies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Server metrics
	Metrics *ServerMetrics `protobuf:"bytes,5,opt,name=metrics,proto3,oneof" json:"metrics,omitempty"`
	// Additional health metadata
	Metadata      map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetDependencies() map[string]*ServiceHealth {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *HealthCheckResponse) GetMetrics() *ServerMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *HealthCheckResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ServiceHealth represents the health of a specific service/dependency
type ServiceHealth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Health status (healthy, degraded, unhealthy)
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Response time in milliseconds
	LatencyMs int64 `protobuf:"varint,2,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// Human-readable status message
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Last successful check timestamp
	LastSuccess *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_success,json=lastSuccess,proto3" json:"last_success,omitempty"`
	// Number of consecutive failures
	FailureCount int32 `protobuf:"varint,5,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	// Additional service-specific details
	Details       map[string]string `protobuf:"bytes,6,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceHealth) Reset() {
	*x = ServiceHealth{}
	mi := &file_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceHealth) ProtoMessage() {}

func (x *ServiceHealth) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceHealth.ProtoReflect.Descriptor instead.
func (*ServiceHealth) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceHealth) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServiceHealth) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ServiceHealth) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServiceHealth) GetLastSuccess() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSuccess
	}
	return nil
}

func (x *ServiceHealth) GetFailureCount() int32 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *ServiceHealth) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// ServerMetrics provides runtime metrics about the gRPC server
type ServerMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of active connections
	ActiveConnections int64 `protobuf:"varint,1,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	// Current requests per second
	RequestsPerSecond float64 `protobuf:"fixed64,2,opt,name=requests_per_second,json=requestsPerSecond,proto3" json:"requests_per_second,omitempty"`
	// Average request latency in milliseconds
	AverageLatencyMs float64 `protobuf:"fixed64,3,opt,name=average_latency_ms,json=averageLatencyMs,proto3" json:"average_latency_ms,omitempty"`
	// Error rate (percentage)
	ErrorRate float64 `protobuf:"fixed64,4,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	// Server uptime
	Uptime *durationpb.Duration `protobuf:"bytes,5,opt,name=uptime,proto3" json:"uptime,omitempty"`
	// Memory usage in bytes
	MemoryUsageBytes int64 `protobuf:"varint,6,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`
	// CPU usage percentage
	CpuUsagePercent float64 `protobuf:"fixed64,7,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	// Number of goroutines (Go-specific)
	Goroutines int64 `protobuf:"varint,8,opt,name=goroutines,proto3" json:"goroutines,omitempty"`
	// Circuit breaker states
	CircuitBreakers map[string]*CircuitBreakerState `protobuf:"bytes,9,rep,name=circuit_breakers,json=circuitBreakers,proto3" json:"circuit_breakers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Rate limiter states
	RateLimiters  map[string]*RateLimiterState `protobuf:"bytes,10,rep,name=rate_limiters,json=rateLimiters,proto3" json:"rate_limiters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMetrics) Reset() {
	*x = ServerMetrics{}
	mi := &file_health_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMetrics) ProtoMessage() {}

func (x *ServerMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMetrics.ProtoReflect.Descriptor instead.
func (*ServerMetrics) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{3}
}

func (x *ServerMetrics) GetActiveConnections() int64 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *ServerMetrics) GetRequestsPerSecond() float64 {
	if x != nil {
		return x.RequestsPerSecond
	}
	return 0
}

func (x *ServerMetrics) GetAverageLatencyMs() float64 {
	if x != nil {
		return x.AverageLatencyMs
	}
	return 0
}

func (x *ServerMetrics) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *ServerMetrics) GetUptime() *durationpb.Duration {
	if x != nil {
		return x.Uptime
	}
	return nil
}

func (x *ServerMetrics) GetMemoryUsageBytes() int64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

func (x *ServerMetrics) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *ServerMetrics) GetGoroutines() int64 {
	if x != nil {
		return x.Goroutines
	}
	return 0
}

func (x *ServerMetrics) GetCircuitBreakers() map[string]*CircuitBreakerState {
	if x != nil {
		return x.CircuitBreakers
	}
	return nil
}

func (x *ServerMetrics) GetRateLimiters() map[string]*RateLimiterState {
	if x != nil {
		return x.RateLimiters
	}
	return nil
}

// CircuitBreakerState represents the state of a circuit breaker
type CircuitBreakerState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current state (closed, open, half-open)
	State string `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	// Number of failures
	FailureCount int64 `protobuf:"varint,2,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	// Success count (in half-open state)
	SuccessCount int64 `protobuf:"varint,3,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	// When the circuit breaker will attempt recovery
	NextAttempt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=next_attempt,json=nextAttempt,proto3" json:"next_attempt,omitempty"`
	// Last state change timestamp
	LastStateChange *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_state_change,json=lastStateChange,proto3" json:"last_state_change,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CircuitBreakerState) Reset() {
	*x = CircuitBreakerState{}
	mi := &file_health_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CircuitBreakerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CircuitBreakerState) ProtoMessage() {}

func (x *CircuitBreakerState) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CircuitBreakerState.ProtoReflect.Descriptor instead.
func (*CircuitBreakerState) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{4}
}

func (x *CircuitBreakerState) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CircuitBreakerState) GetFailureCount() int64 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *CircuitBreakerState) GetSuccessCount() int64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *CircuitBreakerState) GetNextAttempt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextAttempt
	}
	return nil
}

func (x *CircuitBreakerState) GetLastStateChange() *timestamppb.Timestamp {
	if x != nil {
		return x.LastStateChange
	}
	return nil
}

// RateLimiterState represents the state of a rate limiter
type RateLimiterState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current tokens available
	AvailableTokens int64 `protobuf:"varint,1,opt,name=available_tokens,json=availableTokens,proto3" json:"available_tokens,omitempty"`
	// Maximum tokens (bucket size)
	MaxTokens int64 `protobuf:"varint,2,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	// Refill rate (tokens per second)
	RefillRate float64 `protobuf:"fixed64,3,opt,name=refill_rate,json=refillRate,proto3" json:"refill_rate,omitempty"`
	// Next refill timestamp
	NextRefill *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=next_refill,json=nextRefill,proto3" json:"next_refill,omitempty"`
	// Number of rejected requests
	RejectedCount int64 `protobuf:"varint,5,opt,name=rejected_count,json=rejectedCount,proto3" json:"rejected_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimiterState) Reset() {
	*x = RateLimiterState{}
	mi := &file_health_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimiterState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimiterState) ProtoMessage() {}

func (x *RateLimiterState) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimiterState.ProtoReflect.Descriptor instead.
func (*RateLimiterState) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{5}
}

func (x *RateLimiterState) GetAvailableTokens() int64 {
	if x != nil {
		return x.AvailableTokens
	}
	return 0
}

func (x *RateLimiterState) GetMaxTokens() int64 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *RateLimiterState) GetRefillRate() float64 {
	if x != nil {
		return x.RefillRate
	}
	return 0
}

func (x *RateLimiterState) GetNextRefill() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRefill
	}
	return nil
}

func (x *RateLimiterState) GetRejectedCount() int64 {
	if x != nil {
		return x.RejectedCount
	}
	return 0
}

var File_health_proto protoreflect.FileDescriptor

const file_health_proto_rawDesc = "" +
	"\n" +
	"\fhealth.proto\x12\fhuefy.sdk.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x99\x01\n" +
	"\x12HealthCheckRequest\x121\n" +
	"\x14include_dependencies\x18\x01 \x01(\bR\x13includeDependencies\x12'\n" +
	"\x0finclude_metrics\x18\x02 \x01(\bR\x0eincludeMetrics\x12'\n" +
	"\x0finclude_version\x18\x03 \x01(\bR\x0eincludeVersion\"\x8a\x04\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12W\n" +
	"\fdependencies\x18\x04 \x03(\v23.huefy.sdk.v1.HealthCheckResponse.DependenciesEntryR\fdependencies\x12:\n" +
	"\ametrics\x18\x05 \x01(\v2\x1b.huefy.sdk.v1.ServerMetricsH\x00R\ametrics\x88\x01\x01\x12K\n" +
	"\bmetadata\x18\x06 \x03(\v2/.huefy.sdk.v1.HealthCheckResponse.MetadataEntryR\bmetadata\x1a\\\n" +
	"\x11DependenciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.huefy.sdk.v1.ServiceHealthR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\n" +
	"\n" +
	"\b_metrics\"\xc4\x02\n" +
	"\rServiceHealth\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x02 \x01(\x03R\tlatencyMs\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12=\n" +
	"\flast_success\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vlastSuccess\x12#\n" +
	"\rfailure_count\x18\x05 \x01(\x05R\ffailureCount\x12B\n" +
	"\adetails\x18\x06 \x03(\v2(.huefy.sdk.v1.ServiceHealth.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe1\x05\n" +
	"\rServerMetrics\x12-\n" +
	"\x12active_connections\x18\x01 \x01(\x03R\x11activeConnections\x12.\n" +
	"\x13requests_per_second\x18\x02 \x01(\x01R\x11requestsPerSecond\x12,\n" +
	"\x12average_latency_ms\x18\x03 \x01(\x01R\x10averageLatencyMs\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x04 \x01(\x01R\terrorRate\x121\n" +
	"\x06uptime\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x06uptime\x12,\n" +
	"\x12memory_usage_bytes\x18\x06 \x01(\x03R\x10memoryUsageBytes\x12*\n" +
	"\x11cpu_usage_percent\x18\a \x01(\x01R\x0fcpuUsagePercent\x12\x1e\n" +
	"\n" +
	"goroutines\x18\b \x01(\x03R\n" +
	"goroutines\x12[\n" +
	"\x10circuit_breakers\x18\t \x03(\v20.huefy.sdk.v1.ServerMetrics.CircuitBreakersEntryR\x0fcircuitBreakers\x12R\n" +
	"\rrate_limiters\x18\n" +
	" \x03(\v2-.huefy.sdk.v1.ServerMetrics.RateLimitersEntryR\frateLimiters\x1ae\n" +
	"\x14CircuitBreakersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.huefy.sdk.v1.CircuitBreakerStateR\x05value:\x028\x01\x1a_\n" +
	"\x11RateLimitersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.huefy.sdk.v1.RateLimiterStateR\x05value:\x028\x01\"\xfc\x01\n" +
	"\x13CircuitBreakerState\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12#\n" +
	"\rfailure_count\x18\x02 \x01(\x03R\ffailureCount\x12#\n" +
	"\rsuccess_count\x18\x03 \x01(\x03R\fsuccessCount\x12=\n" +
	"\fnext_attempt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vnextAttempt\x12F\n" +
	"\x11last_state_change\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastStateChange\"\xe1\x01\n" +
	"\x10RateLimiterState\x12)\n" +
	"\x10available_tokens\x18\x01 \x01(\x03R\x0favailableTokens\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x02 \x01(\x03R\tmaxTokens\x12\x1f\n" +
	"\vrefill_rate\x18\x03 \x01(\x01R\n" +
	"refillRate\x12;\n" +
	"\vnext_refill\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"nextRefill\x12%\n" +
	"\x0erejected_count\x18\x05 \x01(\x03R\rrejectedCountB7Z5github.com/teracrafts/huefy-sdk/core/kernel/pb/sdk/v1b\x06proto3"

var (
	file_health_proto_rawDescOnce sync.Once
	file_health_proto_rawDescData []byte
)

func file_health_proto_rawDescGZIP() []byte {
	file_health_proto_rawDescOnce.Do(func() {
		file_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_health_proto_rawDesc), len(file_health_proto_rawDesc)))
	})
	return file_health_proto_rawDescData
}

var file_health_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_health_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),    // 0: huefy.sdk.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 1: huefy.sdk.v1.HealthCheckResponse
	(*ServiceHealth)(nil),         // 2: huefy.sdk.v1.ServiceHealth
	(*ServerMetrics)(nil),         // 3: huefy.sdk.v1.ServerMetrics
	(*CircuitBreakerState)(nil),   // 4: huefy.sdk.v1.CircuitBreakerState
	(*RateLimiterState)(nil),      // 5: huefy.sdk.v1.RateLimiterState
	nil,                           // 6: huefy.sdk.v1.HealthCheckResponse.DependenciesEntry
	nil,                           // 7: huefy.sdk.v1.HealthCheckResponse.MetadataEntry
	nil,                           // 8: huefy.sdk.v1.ServiceHealth.DetailsEntry
	nil,                           // 9: huefy.sdk.v1.ServerMetrics.CircuitBreakersEntry
	nil,                           // 10: huefy.sdk.v1.ServerMetrics.RateLimitersEntry
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 12: google.protobuf.Duration
}
var file_health_proto_depIdxs = []int32{
	11, // 0: huefy.sdk.v1.HealthCheckResponse.timestamp:type_name -> google.protobuf.Timestamp
	6,  // 1: huefy.sdk.v1.HealthCheckResponse.dependencies:type_name -> huefy.sdk.v1.HealthCheckResponse.DependenciesEntry
	3,  // 2: huefy.sdk.v1.HealthCheckResponse.metrics:type_name -> huefy.sdk.v1.ServerMetrics
	7,  // 3: huefy.sdk.v1.HealthCheckResponse.metadata:type_name -> huefy.sdk.v1.HealthCheckResponse.MetadataEntry
	11, // 4: huefy.sdk.v1.ServiceHealth.last_success:type_name -> google.protobuf.Timestamp
	8,  // 5: huefy.sdk.v1.ServiceHealth.details:type_name -> huefy.sdk.v1.ServiceHealth.DetailsEntry
	12, // 6: huefy.sdk.v1.ServerMetrics.uptime:type_name -> google.protobuf.Duration
	9,  // 7: huefy.sdk.v1.ServerMetrics.circuit_breakers:type_name -> huefy.sdk.v1.ServerMetrics.CircuitBreakersEntry
	10, // 8: huefy.sdk.v1.ServerMetrics.rate_limiters:type_name -> huefy.sdk.v1.ServerMetrics.RateLimitersEntry
	11, // 9: huefy.sdk.v1.CircuitBreakerState.next_attempt:type_name -> google.protobuf.Timestamp
	11, // 10: huefy.sdk.v1.CircuitBreakerState.last_state_change:type_name -> google.protobuf.Timestamp
	11, // 11: huefy.sdk.v1.RateLimiterState.next_refill:type_name -> google.protobuf.Timestamp
	2,  // 12: huefy.sdk.v1.HealthCheckResponse.DependenciesEntry.value:type_name -> huefy.sdk.v1.ServiceHealth
	4,  // 13: huefy.sdk.v1.ServerMetrics.CircuitBreakersEntry.value:type_name -> huefy.sdk.v1.CircuitBreakerState
	5,  // 14: huefy.sdk.v1.ServerMetrics.RateLimitersEntry.value:type_name -> huefy.sdk.v1.RateLimiterState
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_health_proto_init() }
func file_health_proto_init() {
	if File_health_proto != nil {
		return
	}
	file_health_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_health_proto_rawDesc), len(file_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_health_proto_goTypes,
		DependencyIndexes: file_health_proto_depIdxs,
		MessageInfos:      file_health_proto_msgTypes,
	}.Build()
	File_health_proto = out.File
	file_health_proto_goTypes = nil
	file_health_proto_depIdxs = nil
}
