// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: sdk.service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SDKService_SendEmail_FullMethodName           = "/huefy.sdk.v1.SDKService/SendEmail"
	SDKService_SendBulkEmail_FullMethodName       = "/huefy.sdk.v1.SDKService/SendBulkEmail"
	SDKService_SendBulkEmailStream_FullMethodName = "/huefy.sdk.v1.SDKService/SendBulkEmailStream"
	SDKService_SendEmailStream_FullMethodName     = "/huefy.sdk.v1.SDKService/SendEmailStream"
	SDKService_HealthCheck_FullMethodName         = "/huefy.sdk.v1.SDKService/HealthCheck"
	SDKService_TestAPIKey_FullMethodName          = "/huefy.sdk.v1.SDKService/TestAPIKey"
)

// SDKServiceClient is the client API for SDKService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SDKService provides the main gRPC interface for SDK clients
type SDKServiceClient interface {
	// SendEmail sends a single templated email
	SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error)
	// SendBulkEmail sends multiple emails in a single request
	SendBulkEmail(ctx context.Context, in *SendBulkEmailRequest, opts ...grpc.CallOption) (*SendBulkEmailResponse, error)
	// SendBulkEmailStream sends bulk emails and streams status updates
	SendBulkEmailStream(ctx context.Context, in *SendBulkEmailRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EmailStatusUpdate], error)
	// SendEmailStream allows bidirectional streaming of email requests and responses
	SendEmailStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SendEmailRequest, SendEmailResponse], error)
	// HealthCheck returns the service health status
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// TestAPIKey validates an API key and returns metadata
	TestAPIKey(ctx context.Context, in *TestAPIKeyRequest, opts ...grpc.CallOption) (*TestAPIKeyResponse, error)
}

type sDKServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSDKServiceClient(cc grpc.ClientConnInterface) SDKServiceClient {
	return &sDKServiceClient{cc}
}

func (c *sDKServiceClient) SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendEmailResponse)
	err := c.cc.Invoke(ctx, SDKService_SendEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDKServiceClient) SendBulkEmail(ctx context.Context, in *SendBulkEmailRequest, opts ...grpc.CallOption) (*SendBulkEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendBulkEmailResponse)
	err := c.cc.Invoke(ctx, SDKService_SendBulkEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDKServiceClient) SendBulkEmailStream(ctx context.Context, in *SendBulkEmailRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EmailStatusUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SDKService_ServiceDesc.Streams[0], SDKService_SendBulkEmailStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendBulkEmailRequest, EmailStatusUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SDKService_SendBulkEmailStreamClient = grpc.ServerStreamingClient[EmailStatusUpdate]

func (c *sDKServiceClient) SendEmailStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SendEmailRequest, SendEmailResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SDKService_ServiceDesc.Streams[1], SDKService_SendEmailStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendEmailRequest, SendEmailResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SDKService_SendEmailStreamClient = grpc.BidiStreamingClient[SendEmailRequest, SendEmailResponse]

func (c *sDKServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, SDKService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDKServiceClient) TestAPIKey(ctx context.Context, in *TestAPIKeyRequest, opts ...grpc.CallOption) (*TestAPIKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestAPIKeyResponse)
	err := c.cc.Invoke(ctx, SDKService_TestAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SDKServiceServer is the server API for SDKService service.
// All implementations must embed UnimplementedSDKServiceServer
// for forward compatibility.
//
// SDKService provides the main gRPC interface for SDK clients
type SDKServiceServer interface {
	// SendEmail sends a single templated email
	SendEmail(context.Context, *SendEmailRequest) (*SendEmailResponse, error)
	// SendBulkEmail sends multiple emails in a single request
	SendBulkEmail(context.Context, *SendBulkEmailRequest) (*SendBulkEmailResponse, error)
	// SendBulkEmailStream sends bulk emails and streams status updates
	SendBulkEmailStream(*SendBulkEmailRequest, grpc.ServerStreamingServer[EmailStatusUpdate]) error
	// SendEmailStream allows bidirectional streaming of email requests and responses
	SendEmailStream(grpc.BidiStreamingServer[SendEmailRequest, SendEmailResponse]) error
	// HealthCheck returns the service health status
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// TestAPIKey validates an API key and returns metadata
	TestAPIKey(context.Context, *TestAPIKeyRequest) (*TestAPIKeyResponse, error)
	mustEmbedUnimplementedSDKServiceServer()
}

// UnimplementedSDKServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSDKServiceServer struct{}

func (UnimplementedSDKServiceServer) SendEmail(context.Context, *SendEmailRequest) (*SendEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmail not implemented")
}
func (UnimplementedSDKServiceServer) SendBulkEmail(context.Context, *SendBulkEmailRequest) (*SendBulkEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendBulkEmail not implemented")
}
func (UnimplementedSDKServiceServer) SendBulkEmailStream(*SendBulkEmailRequest, grpc.ServerStreamingServer[EmailStatusUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method SendBulkEmailStream not implemented")
}
func (UnimplementedSDKServiceServer) SendEmailStream(grpc.BidiStreamingServer[SendEmailRequest, SendEmailResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SendEmailStream not implemented")
}
func (UnimplementedSDKServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedSDKServiceServer) TestAPIKey(context.Context, *TestAPIKeyRequest) (*TestAPIKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestAPIKey not implemented")
}
func (UnimplementedSDKServiceServer) mustEmbedUnimplementedSDKServiceServer() {}
func (UnimplementedSDKServiceServer) testEmbeddedByValue()                    {}

// UnsafeSDKServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SDKServiceServer will
// result in compilation errors.
type UnsafeSDKServiceServer interface {
	mustEmbedUnimplementedSDKServiceServer()
}

func RegisterSDKServiceServer(s grpc.ServiceRegistrar, srv SDKServiceServer) {
	// If the following call pancis, it indicates UnimplementedSDKServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SDKService_ServiceDesc, srv)
}

func _SDKService_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDKServiceServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDKService_SendEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDKServiceServer).SendEmail(ctx, req.(*SendEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDKService_SendBulkEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendBulkEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDKServiceServer).SendBulkEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDKService_SendBulkEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDKServiceServer).SendBulkEmail(ctx, req.(*SendBulkEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDKService_SendBulkEmailStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SendBulkEmailRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SDKServiceServer).SendBulkEmailStream(m, &grpc.GenericServerStream[SendBulkEmailRequest, EmailStatusUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SDKService_SendBulkEmailStreamServer = grpc.ServerStreamingServer[EmailStatusUpdate]

func _SDKService_SendEmailStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SDKServiceServer).SendEmailStream(&grpc.GenericServerStream[SendEmailRequest, SendEmailResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SDKService_SendEmailStreamServer = grpc.BidiStreamingServer[SendEmailRequest, SendEmailResponse]

func _SDKService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDKServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDKService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDKServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDKService_TestAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDKServiceServer).TestAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDKService_TestAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDKServiceServer).TestAPIKey(ctx, req.(*TestAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SDKService_ServiceDesc is the grpc.ServiceDesc for SDKService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SDKService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "huefy.sdk.v1.SDKService",
	HandlerType: (*SDKServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmail",
			Handler:    _SDKService_SendEmail_Handler,
		},
		{
			MethodName: "SendBulkEmail",
			Handler:    _SDKService_SendBulkEmail_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _SDKService_HealthCheck_Handler,
		},
		{
			MethodName: "TestAPIKey",
			Handler:    _SDKService_TestAPIKey_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendBulkEmailStream",
			Handler:       _SDKService_SendBulkEmailStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendEmailStream",
			Handler:       _SDKService_SendEmailStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "sdk.service.proto",
}
