// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: sdk.service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_sdk_service_proto protoreflect.FileDescriptor

const file_sdk_service_proto_rawDesc = "" +
	"\n" +
	"\x11sdk.service.proto\x12\fhuefy.sdk.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\vemail.proto\x1a\fcommon.proto\x1a\fhealth.proto2\x8f\x04\n" +
	"\n" +
	"SDKService\x12L\n" +
	"\tSendEmail\x12\x1e.huefy.sdk.v1.SendEmailRequest\x1a\x1f.huefy.sdk.v1.SendEmailResponse\x12X\n" +
	"\rSendBulkEmail\x12\".huefy.sdk.v1.SendBulkEmailRequest\x1a#.huefy.sdk.v1.SendBulkEmailResponse\x12\\\n" +
	"\x13SendBulkEmailStream\x12\".huefy.sdk.v1.SendBulkEmailRequest\x1a\x1f.huefy.sdk.v1.EmailStatusUpdate0\x01\x12V\n" +
	"\x0fSendEmailStream\x12\x1e.huefy.sdk.v1.SendEmailRequest\x1a\x1f.huefy.sdk.v1.SendEmailResponse(\x010\x01\x12R\n" +
	"\vHealthCheck\x12 .huefy.sdk.v1.HealthCheckRequest\x1a!.huefy.sdk.v1.HealthCheckResponse\x12O\n" +
	"\n" +
	"TestAPIKey\x12\x1f.huefy.sdk.v1.TestAPIKeyRequest\x1a .huefy.sdk.v1.TestAPIKeyResponseB7Z5github.com/teracrafts/huefy-sdk/core/kernel/pb/sdk/v1b\x06proto3"

var file_sdk_service_proto_goTypes = []any{
	(*SendEmailRequest)(nil),      // 0: huefy.sdk.v1.SendEmailRequest
	(*SendBulkEmailRequest)(nil),  // 1: huefy.sdk.v1.SendBulkEmailRequest
	(*HealthCheckRequest)(nil),    // 2: huefy.sdk.v1.HealthCheckRequest
	(*TestAPIKeyRequest)(nil),     // 3: huefy.sdk.v1.TestAPIKeyRequest
	(*SendEmailResponse)(nil),     // 4: huefy.sdk.v1.SendEmailResponse
	(*SendBulkEmailResponse)(nil), // 5: huefy.sdk.v1.SendBulkEmailResponse
	(*EmailStatusUpdate)(nil),     // 6: huefy.sdk.v1.EmailStatusUpdate
	(*HealthCheckResponse)(nil),   // 7: huefy.sdk.v1.HealthCheckResponse
	(*TestAPIKeyResponse)(nil),    // 8: huefy.sdk.v1.TestAPIKeyResponse
}
var file_sdk_service_proto_depIdxs = []int32{
	0, // 0: huefy.sdk.v1.SDKService.SendEmail:input_type -> huefy.sdk.v1.SendEmailRequest
	1, // 1: huefy.sdk.v1.SDKService.SendBulkEmail:input_type -> huefy.sdk.v1.SendBulkEmailRequest
	1, // 2: huefy.sdk.v1.SDKService.SendBulkEmailStream:input_type -> huefy.sdk.v1.SendBulkEmailRequest
	0, // 3: huefy.sdk.v1.SDKService.SendEmailStream:input_type -> huefy.sdk.v1.SendEmailRequest
	2, // 4: huefy.sdk.v1.SDKService.HealthCheck:input_type -> huefy.sdk.v1.HealthCheckRequest
	3, // 5: huefy.sdk.v1.SDKService.TestAPIKey:input_type -> huefy.sdk.v1.TestAPIKeyRequest
	4, // 6: huefy.sdk.v1.SDKService.SendEmail:output_type -> huefy.sdk.v1.SendEmailResponse
	5, // 7: huefy.sdk.v1.SDKService.SendBulkEmail:output_type -> huefy.sdk.v1.SendBulkEmailResponse
	6, // 8: huefy.sdk.v1.SDKService.SendBulkEmailStream:output_type -> huefy.sdk.v1.EmailStatusUpdate
	4, // 9: huefy.sdk.v1.SDKService.SendEmailStream:output_type -> huefy.sdk.v1.SendEmailResponse
	7, // 10: huefy.sdk.v1.SDKService.HealthCheck:output_type -> huefy.sdk.v1.HealthCheckResponse
	8, // 11: huefy.sdk.v1.SDKService.TestAPIKey:output_type -> huefy.sdk.v1.TestAPIKeyResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sdk_service_proto_init() }
func file_sdk_service_proto_init() {
	if File_sdk_service_proto != nil {
		return
	}
	file_email_proto_init()
	file_common_proto_init()
	file_health_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_service_proto_rawDesc), len(file_sdk_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sdk_service_proto_goTypes,
		DependencyIndexes: file_sdk_service_proto_depIdxs,
	}.Build()
	File_sdk_service_proto = out.File
	file_sdk_service_proto_goTypes = nil
	file_sdk_service_proto_depIdxs = nil
}
